import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:task_tracker/config/brand.dart';

class SettingsService extends ChangeNotifier {
  String _language = 'en';
  ThemeMode _themeMode = ThemeMode.light;
  Color _accentColor = Brand.primary;
  List<Map<String, String>> _rememberedAccounts = [];
  String _currentRole = '';
  bool _notificationsEnabled = true;

  String get language => _language;
  ThemeMode get themeMode => _themeMode;
  Color get accentColor => _accentColor;
  List<Map<String, String>> get rememberedAccounts => _rememberedAccounts;
  String get currentRole => _currentRole;
  bool get notificationsEnabled => _notificationsEnabled;
  set currentRole(String role) {
    _currentRole = role;
    notifyListeners();
  }

  static const _langKey = 'language';
  static const _themeKey = 'theme';
  static const _accentKey = 'accent';
  static const _accountsKey = 'accounts';
  static const _notifEnabledKey = 'notifications_enabled';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _language = prefs.getString(_langKey) ?? 'en';
    final themeStr = prefs.getString(_themeKey) ?? 'light';
    _themeMode = themeStr == 'dark' ? ThemeMode.dark : ThemeMode.light;
    final accentStr = prefs.getInt(_accentKey) ?? Brand.primary.toARGB32();
    _accentColor = Color(accentStr);
    final accountsJson = prefs.getString(_accountsKey);
    if (accountsJson != null) {
      _rememberedAccounts = (accountsJson.split('|').where((s) => s.isNotEmpty).map((s) {
        final parts = s.split(',');
        if (parts.length >= 2) return {'email': parts[0], 'name': parts[1]};
        return {'email': parts[0], 'name': parts[0]};
      })).toList();
    }
    _notificationsEnabled = prefs.getBool(_notifEnabledKey) ?? true;
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _language = lang;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, lang);
  }

  Future<void> setThemeMode(ThemeMode mode) async {
    _themeMode = mode;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_themeKey, mode == ThemeMode.dark ? 'dark' : 'light');
  }

  Future<void> setAccentColor(Color color) async {
    _accentColor = color;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_accentKey, color.toARGB32());
  }

  Future<void> setNotificationsEnabled(bool enabled) async {
    _notificationsEnabled = enabled;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifEnabledKey, enabled);
  }

  Future<void> addAccount(String email, String name) async {
    _rememberedAccounts.removeWhere((a) => a['email'] == email);
    _rememberedAccounts.insert(0, {'email': email, 'name': name});
    notifyListeners();
    await _saveAccounts();
  }

  Future<void> removeAccount(String email) async {
    _rememberedAccounts.removeWhere((a) => a['email'] == email);
    notifyListeners();
    await _saveAccounts();
  }

  Future<void> _saveAccounts() async {
    final prefs = await SharedPreferences.getInstance();
    final json = _rememberedAccounts.map((a) => '${a['email']},${a['name']}').join('|');
    await prefs.setString(_accountsKey, json);
  }

  String t(String key) {
    return _strings[_language]?[key] ?? _strings['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_name': 'Task Tracker',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',

      'email': 'Email',
      'password': 'Password',
      'no_account': "Don't have an account? Create one",
      'has_account': 'Already have an account? Sign In',
      'select_role': 'Select Your Role',
      'i_am_manager': 'I am a Manager',
      'i_am_employee': 'I am an Employee',
      'manager_dashboard': 'Manager Dashboard',
      'my_tasks': 'My Tasks',
      'new_task': 'New Task',
      'title': 'Title',
      'description': 'Description',
      'employee_name': 'Employee Name',
      'employee_email': 'Employee Email',
      'assign_to_all': 'Assign to all employees',
      'customer': 'Customer',
      'car_thing': 'Car / Thing',
      'preset_task': 'Preset Task',
      'custom_task': 'Custom Task',
      'create': 'Create',
      'cancel': 'Cancel',
      'pending': 'Pending',
      'doing': 'In Progress',
      'done': 'Done',
      'claim': 'Claim Task',
      'claim_hint': 'I will do this task',
      'complete_with_photo': 'Take Photo & Complete',
      'uploading': 'Uploading...',
      'reset_task': 'Reset Task',
      'reset_confirm': 'Mark this task as incomplete again?',
      'no_tasks': 'No tasks yet',
      'no_tasks_assigned': 'No tasks assigned yet',
      'tasks': 'tasks',
      'tasks_pending': 'pending',
      'tasks_done': 'done',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'accent_color': 'Accent Color',
      'accounts': 'Accounts',
      'remembered_accounts': 'Remembered Accounts',
      'delete_account': 'Remove from device',
      'confirm_delete_account': 'Remove this account from this device?',
      'create_first_task': 'Create First Task',
      'task_completed': 'Task completed! Photo proof submitted.',
      'failed': 'Failed',
      'assigned_to': 'Assigned to',
      'created': 'Created',
      'completed': 'Completed',
      'proof_photo': 'Proof Photo',
      'no_description': 'No description',
      'preset_tasks': 'Preset Tasks',
      'manage_presets': 'Manage Presets',
      'new_preset': 'New Preset',
      'preset_name': 'Preset Name',
      'default_desc': 'Default description',
      'req_car': 'Ask for car/thing',
      'save': 'Save',
      'delete': 'Delete',
      'claimed_by': 'In progress by',
      'free': 'Available',
      'confirm_logout': 'Sign out?',
      'pending_review': 'Pending Review',
      'manage_employees': 'Manage Employees',
      'manage_items': 'Manage Preset Items',
      'problems': 'Problems',
      'report_problem': 'Report Problem',
      'new_employee': 'New Employee',
      'manager_password': 'Your Password (Manager)',
      'no_employees': 'No employees yet',
      'no_items': 'No preset items yet',
      'open': 'Open',
      'resolved': 'Resolved',
      'convert_to_task': 'Convert to Task',
      'none': 'None',
      'take_photo': 'Take Photo',
      'retake': 'Retake',
      'send': 'Send',
      'approve': 'Approve',
      'reject': 'Reject',
      'reassign': 'Reassign',
      'tasks_tab': 'Tasks',
      'problems_tab': 'Problems',
      'item_name': 'Item Name',
      'start_task': 'Start Task',
      'filter_active': 'Active',
      'filter_all': 'All',
      'filter_pending': 'Pending',
      'filter_doing': 'In Progress',
      'filter_review': 'Pending Review',
      'filter_completed': 'Completed',
      'filter_open': 'Open',
      'filter_assigned': 'Assigned',
      'filter_resolved': 'Resolved',
      'show_password': 'Show password',
      'hide_password': 'Hide password',
      'search': 'Search',
      'edit_task': 'Edit Task',
      'task_started': 'Task started',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'saved': 'Saved',
      'task_reset': 'Task reset',
      'rejection_reason': 'Rejection reason',
      'reject_reason': 'Reason for rejection?',
      'reject_reason_hint': 'Enter a reason…',
      'tap_to_zoom': 'Tap to zoom',
      'history': 'History',
      'started': 'Started',
      'submitted_proof': 'Submitted proof',
      'status_change': 'Status changed',
      'by': 'by',
      'rename_employee': 'Rename Employee',
      'total_tasks': 'Total Tasks',
      'open_problems': 'Open Problems',
      'export_data': 'Export Data',
      'exported': 'Data copied to clipboard',
      'data': 'Data',
      'about': 'About',
      'check_for_updates': 'Check for Updates',
      'push_notifications': 'Push Notifications',
      'push_notifications_desc': 'Receive push notifications on this device',
      'checking_for_updates': 'Checking for updates...',
      'account_not_configured': 'Account Not Configured',
      'contact_administrator': 'Contact your administrator to set up your account.',
      'up_to_date': 'You are up to date!',
      'update_available': 'Update Available',
      'open_web_version': 'Open Web Version',
      'notifications': 'Notifications',
      'notification_preferences': 'Notification Preferences',
      'manager_notifications': 'Manager Notifications',
      'employee_notifications': 'Employee Notifications',
      'mark_all_read': 'Mark all read',
      'no_notifications': 'No notifications yet',
      'notify_task_assigned': 'Task Assigned',
      'notify_task_assigned_desc': 'When a new task is assigned to you',
      'notify_task_started': 'Task Started',
      'notify_task_started_desc': 'When an employee starts working on a task',
      'notify_task_submitted': 'Task Submitted for Review',
      'notify_task_submitted_desc': 'When an employee submits proof of completion',
      'notify_task_approved': 'Task Approved',
      'notify_task_approved_desc': 'When your completed task is approved',
      'notify_task_rejected': 'Task Rejected',
      'notify_task_rejected_desc': 'When your completed task is rejected',
      'notify_task_completed_manager': 'Task Completed',
      'notify_task_completed_manager_desc': 'When a task is fully completed',
      'notify_problem_reported': 'Problem Reported',
      'notify_problem_reported_desc': 'When an employee reports a new problem',
      'notify_problem_converted': 'Problem Converted to Task',
      'notify_problem_converted_desc': 'When a reported problem becomes a task',
      'notify_task_status_changed': 'Task Status Changed',
      'notify_task_status_changed_desc': 'When any task status changes',
      'notif_task_assigned_msg': 'has been assigned to you',
      'notif_task_started_msg': '{name} started working on',
      'notif_task_submitted_msg': '{name} submitted for review',
      'notif_task_approved_msg': 'has been approved',
      'notif_task_rejected_msg': 'was rejected',
      'notif_task_reassigned_msg': 'You have been assigned a task',
      'notif_problem_reported_msg': '{name} reported a problem',
      'notif_problem_resolved_msg': 'Your reported problem has been resolved',
      'notif_problem_converted_msg': 'Your reported problem has been converted to a task',
    },
    'fr': {
      'app_name': 'Gestionnaire de Tâches',
      'sign_in': 'Connexion',
      'sign_up': "S'inscrire",
      'sign_out': 'Déconnexion',

      'email': 'Email',
      'password': 'Mot de passe',
      'no_account': 'Pas de compte? Créez-en un',
      'has_account': 'Déjà un compte? Connectez-vous',
      'select_role': 'Choisissez votre rôle',
      'i_am_manager': 'Je suis Manager',
      'i_am_employee': 'Je suis Employé',
      'manager_dashboard': 'Tableau de Bord',
      'my_tasks': 'Mes Tâches',
      'new_task': 'Nouvelle Tâche',
      'title': 'Titre',
      'description': 'Description',
      'employee_name': "Nom de l'employé",
      'employee_email': "Email de l'employé",
      'assign_to_all': 'Assigner à tous',
      'customer': 'Client',
      'car_thing': 'Voiture / Objet',
      'preset_task': 'Tâche prédéfinie',
      'custom_task': 'Tâche personnalisée',
      'create': 'Créer',
      'cancel': 'Annuler',
      'pending': 'En attente',
      'doing': 'En cours',
      'done': 'Terminé',
      'claim': 'Prendre la tâche',
      'claim_hint': 'Je vais faire cette tâche',
      'complete_with_photo': 'Photo & Terminer',
      'uploading': 'Téléchargement...',
      'reset_task': 'Réinitialiser',
      'reset_confirm': 'Marquer comme non terminé?',
      'no_tasks': 'Aucune tâche',
      'no_tasks_assigned': 'Aucune tâche assignée',
      'tasks': 'tâches',
      'tasks_pending': 'en attente',
      'tasks_done': 'terminées',
      'settings': 'Paramètres',
      'language': 'Langue',
      'theme': 'Thème',
      'light': 'Clair',
      'dark': 'Sombre',
      'accent_color': 'Couleur',
      'accounts': 'Comptes',
      'remembered_accounts': 'Comptes enregistrés',
      'delete_account': 'Supprimer',
      'confirm_delete_account': 'Supprimer ce compte?',
      'create_first_task': 'Créer une tâche',
      'task_completed': 'Tâche terminée! Preuve soumise.',
      'failed': 'Échec',
      'assigned_to': 'Assigné à',
      'created': 'Créé',
      'completed': 'Terminé',
      'proof_photo': 'Photo preuve',
      'no_description': 'Aucune description',
      'preset_tasks': 'Tâches prédéfinies',
      'manage_presets': 'Gérer les prédéfinis',
      'new_preset': 'Nouveau prédéfini',
      'preset_name': 'Nom du prédéfini',
      'default_desc': 'Description par défaut',
      'req_car': 'Demander voiture/objet',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'claimed_by': 'En cours par',
      'free': 'Disponible',
      'confirm_logout': 'Se déconnecter?',
      'pending_review': 'En attente de validation',
      'manage_employees': 'Gérer les employés',
      'manage_items': 'Gérer les éléments',
      'problems': 'Problèmes',
      'report_problem': 'Signaler un problème',
      'new_employee': 'Nouvel employé',
      'manager_password': 'Votre mot de passe (gestionnaire)',
      'no_employees': 'Aucun employé',
      'no_items': 'Aucun élément',
      'open': 'Ouvert',
      'resolved': 'Résolu',
      'convert_to_task': 'Convertir en tâche',
      'none': 'Aucun',
      'take_photo': 'Prendre une photo',
      'retake': 'Reprendre',
      'send': 'Envoyer',
      'approve': 'Approuver',
      'reject': 'Rejeter',
      'reassign': 'Réassigner',
      'tasks_tab': 'Tâches',
      'problems_tab': 'Problèmes',
      'item_name': "Nom de l'élément",
      'start_task': 'Commencer la tâche',
      'filter_active': 'Actif',
      'filter_all': 'Tout',
      'filter_pending': 'En attente',
      'filter_doing': 'En cours',
      'filter_review': 'En validation',
      'filter_completed': 'Terminé',
      'filter_open': 'Ouvert',
      'filter_assigned': 'Assigné',
      'filter_resolved': 'Résolu',
      'show_password': 'Afficher le mot de passe',
      'hide_password': 'Cacher le mot de passe',
      'search': 'Rechercher',
      'edit_task': 'Modifier la tâche',
      'task_started': 'Tâche commencée',
      'approved': 'Approuvé',
      'rejected': 'Rejeté',
      'saved': 'Enregistré',
      'task_reset': 'Tâche réinitialisée',
      'rejection_reason': 'Raison du rejet',
      'reject_reason': 'Raison du rejet?',
      'reject_reason_hint': 'Entrez une raison…',
      'tap_to_zoom': 'Appuyez pour zoomer',
      'history': 'Historique',
      'started': 'Commencée',
      'submitted_proof': 'Preuve soumise',
      'status_change': 'Statut modifié',
      'by': 'par',
      'rename_employee': "Renommer l'employé",
      'total_tasks': 'Total des tâches',
      'open_problems': 'Problèmes ouverts',
      'export_data': 'Exporter les données',
      'exported': 'Données copiées dans le presse-papier',
      'data': 'Données',
      'about': 'À propos',
      'check_for_updates': 'Vérifier les mises à jour',
      'push_notifications': 'Notifications push',
      'push_notifications_desc': 'Recevoir les notifications push sur cet appareil',
      'checking_for_updates': 'Vérification des mises à jour...',
      'account_not_configured': 'Compte non configuré',
      'contact_administrator': 'Contactez votre administrateur pour configurer votre compte.',
      'up_to_date': 'Vous êtes à jour !',
      'update_available': 'Mise à jour disponible',
      'open_web_version': 'Ouvrir la version Web',
      'notifications': 'Notifications',
      'notification_preferences': 'Préférences de notification',
      'manager_notifications': 'Notifications du gestionnaire',
      'employee_notifications': "Notifications de l'employé",
      'mark_all_read': 'Tout marquer comme lu',
      'no_notifications': 'Aucune notification',
      'notify_task_assigned': 'Tâche assignée',
      'notify_task_assigned_desc': 'Quand une nouvelle tâche vous est assignée',
      'notify_task_started': 'Tâche commencée',
      'notify_task_started_desc': "Quand un employé commence une tâche",
      'notify_task_submitted': 'Tâche soumise pour validation',
      'notify_task_submitted_desc': "Quand un employé soumet une preuve",
      'notify_task_approved': 'Tâche approuvée',
      'notify_task_approved_desc': "Quand votre tâche terminée est approuvée",
      'notify_task_rejected': 'Tâche rejetée',
      'notify_task_rejected_desc': "Quand votre tâche terminée est rejetée",
      'notify_task_completed_manager': 'Tâche terminée',
      'notify_task_completed_manager_desc': 'Quand une tâche est entièrement terminée',
      'notify_problem_reported': 'Problème signalé',
      'notify_problem_reported_desc': "Quand un employé signale un problème",
      'notify_problem_converted': 'Problème converti en tâche',
      'notify_problem_converted_desc': "Quand un problème devient une tâche",
      'notify_task_status_changed': 'Statut de tâche modifié',
      'notify_task_status_changed_desc': 'Quand le statut d\'une tâche change',
      'notif_task_assigned_msg': 'vous a été assignée',
      'notif_task_started_msg': '{name} a commencé à travailler sur',
      'notif_task_submitted_msg': '{name} a soumis pour validation',
      'notif_task_approved_msg': 'a été approuvée',
      'notif_task_rejected_msg': 'a été rejetée',
      'notif_task_reassigned_msg': 'Une tâche vous a été assignée',
      'notif_problem_reported_msg': '{name} a signalé un problème',
      'notif_problem_resolved_msg': 'Votre problème signalé a été résolu',
      'notif_problem_converted_msg': 'Votre problème signalé a été converti en tâche',
    },
    'ar': {
      'app_name': 'مدير المهام',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'sign_out': 'تسجيل الخروج',

      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'no_account': 'ليس لديك حساب؟ إنشاء واحد',
      'has_account': 'لديك حساب؟ تسجيل الدخول',
      'select_role': 'اختر دورك',
      'i_am_manager': 'أنا مدير',
      'i_am_employee': 'أنا موظف',
      'manager_dashboard': 'لوحة التحكم',
      'my_tasks': 'مهامي',
      'new_task': 'مهمة جديدة',
      'title': 'العنوان',
      'description': 'الوصف',
      'employee_name': 'اسم الموظف',
      'employee_email': 'بريد الموظف',
      'assign_to_all': 'تعيين للجميع',
      'customer': 'العميل',
      'car_thing': 'السيارة / الشيء',
      'preset_task': 'مهمة محددة مسبقاً',
      'custom_task': 'مهمة مخصصة',
      'create': 'إنشاء',
      'cancel': 'إلغاء',
      'pending': 'قيد الانتظار',
      'doing': 'قيد التنفيذ',
      'done': 'مكتمل',
      'claim': 'تولي المهمة',
      'claim_hint': 'سأقوم بهذه المهمة',
      'complete_with_photo': 'تصوير وإكمال',
      'uploading': 'جاري الرفع...',
      'reset_task': 'إعادة المهمة',
      'reset_confirm': 'هل تريد إرجاع المهمة كغير مكتملة؟',
      'no_tasks': 'لا توجد مهام',
      'no_tasks_assigned': 'لا توجد مهام مسندة',
      'tasks': 'مهام',
      'tasks_pending': 'قيد الانتظار',
      'tasks_done': 'مكتملة',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'light': 'فاتح',
      'dark': 'داكن',
      'accent_color': 'اللون الرئيسي',
      'accounts': 'الحسابات',
      'remembered_accounts': 'الحسابات المحفوظة',
      'delete_account': 'حذف من الجهاز',
      'confirm_delete_account': 'حذف هذا الحساب من الجهاز؟',
      'create_first_task': 'إنشاء أول مهمة',
      'task_completed': 'تم إكمال المهمة! تم إرسال الصورة.',
      'failed': 'فشل',
      'assigned_to': 'مسندة إلى',
      'created': 'تم الإنشاء',
      'completed': 'تم الإكمال',
      'proof_photo': 'صورة الإثبات',
      'no_description': 'لا يوجد وصف',
      'preset_tasks': 'مهام محددة مسبقاً',
      'manage_presets': 'إدارة المهام المحددة',
      'new_preset': 'إضافة مهمة محددة',
      'preset_name': 'اسم المهمة',
      'default_desc': 'الوصف الافتراضي',
      'req_car': 'طلب السيارة/الشيء',
      'save': 'حفظ',
      'delete': 'حذف',
      'claimed_by': 'قيد التنفيذ بواسطة',
      'free': 'متاحة',
      'confirm_logout': 'تسجيل الخروج؟',
      'pending_review': 'قيد المراجعة',
      'manage_employees': 'إدارة الموظفين',
      'manage_items': 'إدارة العناصر',
      'problems': 'المشاكل',
      'report_problem': 'الإبلاغ عن مشكلة',
      'new_employee': 'موظف جديد',
      'manager_password': 'كلمة مرورك (مدير)',
      'no_employees': 'لا يوجد موظفون',
      'no_items': 'لا توجد عناصر',
      'open': 'مفتوح',
      'resolved': 'تم الحل',
      'convert_to_task': 'تحويل إلى مهمة',
      'none': 'لا شيء',
      'take_photo': 'التقاط صورة',
      'retake': 'إعادة التصوير',
      'send': 'إرسال',
      'approve': 'موافقة',
      'reject': 'رفض',
      'reassign': 'إعادة تعيين',
      'tasks_tab': 'المهام',
      'problems_tab': 'المشاكل',
      'item_name': 'اسم العنصر',
      'start_task': 'بدء المهمة',
      'filter_active': 'نشط',
      'filter_all': 'الكل',
      'filter_pending': 'قيد الانتظار',
      'filter_doing': 'قيد التنفيذ',
      'filter_review': 'قيد المراجعة',
      'filter_completed': 'مكتمل',
      'filter_open': 'مفتوح',
      'filter_assigned': 'مسند',
      'filter_resolved': 'تم الحل',
      'show_password': 'إظهار كلمة المرور',
      'hide_password': 'إخفاء كلمة المرور',
      'search': 'بحث',
      'edit_task': 'تعديل المهمة',
      'task_started': 'بدأت المهمة',
      'approved': 'تمت الموافقة',
      'rejected': 'تم الرفض',
      'saved': 'تم الحفظ',
      'task_reset': 'تم إعادة تعيين المهمة',
      'rejection_reason': 'سبب الرفض',
      'reject_reason': 'سبب الرفض؟',
      'reject_reason_hint': 'أدخل السبب…',
      'tap_to_zoom': 'اضغط للتكبير',
      'history': 'السجل',
      'started': 'بدأت',
      'submitted_proof': 'تم تقديم الإثبات',
      'status_change': 'تم تغيير الحالة',
      'by': 'بواسطة',
      'rename_employee': 'إعادة تسمية الموظف',
      'total_tasks': 'إجمالي المهام',
      'open_problems': 'المشاكل المفتوحة',
      'export_data': 'تصدير البيانات',
      'exported': 'تم نسخ البيانات إلى الحافظة',
      'data': 'البيانات',
      'about': 'حول',
      'check_for_updates': 'التحقق من التحديثات',
      'push_notifications': 'إشعارات الدفع',
      'push_notifications_desc': 'استقبال إشعارات الدفع على هذا الجهاز',
      'checking_for_updates': 'جاري التحقق من التحديثات...',
      'account_not_configured': 'الحساب غير مكون',
      'contact_administrator': 'اتصل بمسؤولك لإعداد حسابك.',
      'up_to_date': 'أنت تستخدم أحدث إصدار!',
      'update_available': 'تحديث متاح',
      'open_web_version': 'فتح النسخة الويب',
      'notifications': 'الإشعارات',
      'notification_preferences': 'تفضيلات الإشعارات',
      'manager_notifications': 'إشعارات المدير',
      'employee_notifications': 'إشعارات الموظف',
      'mark_all_read': 'تحديد الكل كمقروء',
      'no_notifications': 'لا توجد إشعارات',
      'notify_task_assigned': 'تم تعيين مهمة',
      'notify_task_assigned_desc': 'عند تعيين مهمة جديدة لك',
      'notify_task_started': 'بدأت المهمة',
      'notify_task_started_desc': 'عندما يبدأ موظف في العمل على مهمة',
      'notify_task_submitted': 'تم تقديم المهمة للمراجعة',
      'notify_task_submitted_desc': 'عندما يقدم موظف إثبات الإكمال',
      'notify_task_approved': 'تمت الموافقة على المهمة',
      'notify_task_approved_desc': 'عندما تتم الموافقة على مهمتك المكتملة',
      'notify_task_rejected': 'تم رفض المهمة',
      'notify_task_rejected_desc': 'عندما يتم رفض مهمتك المكتملة',
      'notify_task_completed_manager': 'اكتملت المهمة',
      'notify_task_completed_manager_desc': 'عند اكتمال المهمة بالكامل',
      'notify_problem_reported': 'تم الإبلاغ عن مشكلة',
      'notify_problem_reported_desc': 'عندما يبلغ موظف عن مشكلة جديدة',
      'notify_problem_converted': 'تم تحويل المشكلة إلى مهمة',
      'notify_problem_converted_desc': 'عندما تصبح المشكلة المبلغ عنها مهمة',
      'notify_task_status_changed': 'تم تغيير حالة المهمة',
      'notify_task_status_changed_desc': 'عند تغيير حالة أي مهمة',
      'notif_task_assigned_msg': 'تم تعيينها لك',
      'notif_task_started_msg': '{name} بدأ العمل على',
      'notif_task_submitted_msg': '{name} قدم للمراجعة',
      'notif_task_approved_msg': 'تمت الموافقة عليها',
      'notif_task_rejected_msg': 'تم رفضها',
      'notif_task_reassigned_msg': 'تم تعيين مهمة لك',
      'notif_problem_reported_msg': '{name} أبلغ عن مشكلة',
      'notif_problem_resolved_msg': 'تم حل مشكلتك المبلغ عنها',
      'notif_problem_converted_msg': 'تم تحويل مشكلتك المبلغ عنها إلى مهمة',
    },
  };

  TextDirection get textDirection =>
      _language == 'ar' ? TextDirection.rtl : TextDirection.ltr;
}
